# This will remove the "via ğŸ¹"
[package]
disabled = true

# This removes the "via â˜• v11.0.11" Java version info
[java]
disabled = true

# Set disable = false to show hostname
[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold dimmed white"
disabled = true
